version: '3.8'

services:
  web-app:
    build: .
    image: node:lts
    ports:
      - "8000:8000"
    volumes:
      - .:/web-app
  
  
#   version: '3.6'
# services:
#     postgres:
#         image: postgres:14.4
#         restart: always
#         environment:
#             POSTGRES_USER: root
#             POSTGRES_PASSWORD: admin
#             POSTGRES_DB: test
#         volumes:
#             - ./postgres:/var/lib/postgresql/data
#         ports:
#             - 5432:5432
#     adminer:
#         image: adminer
#         ports:
#             - 9921:8080
# volumes:
#     postgres:
#     adminer:
